// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarmiz.API.Data;

#nullable disable

namespace Tarmiz.API.Migrations
{
    [DbContext(typeof(TarmizDbContext))]
    partial class TarmizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarmiz.API.Models.Listing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ListingId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            ListingId = new Guid("aff847e9-a102-4353-9858-f4a6f1e04c24"),
                            CreatedAt = new DateTime(2025, 4, 23, 12, 45, 46, 734, DateTimeKind.Utc).AddTicks(3349),
                            Description = "This is a sample listing.",
                            Governorate = "Irbid",
                            ImageUrl = "https://example.com/image.jpg",
                            NumberType = "Type Gold",
                            Price = 100.00m,
                            Title = "Sample Listing",
                            UpdatedAt = new DateTime(2025, 4, 23, 12, 45, 46, 734, DateTimeKind.Utc).AddTicks(3350)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
